#!/bin/bash

if [ $# -lt 2 ]; then
    echo 'usage: pyhail-submit <cluster> <py-files>'
    exit 1
fi

cluster=$1
shift
script=$1
shift

echo cluster = $cluster
echo script = $script

HASH=`gsutil cat gs://hail-common/latest-hash.txt`

JAR_FILE=hail-hail-is-master-all-spark2.0.2-$HASH.jar
JAR=gs://hail-common/$JAR_FILE

pyfiles=gs://hail-common/pyhail-hail-is-master-$HASH.zip
for file in "$@"
do
pyfiles="$pyfiles,$file"
done

echo JAR = $JAR
echo pyfiles = $pyfiles

gcloud dataproc jobs submit pyspark \
       --cluster $cluster \
       --files=$JAR \
       --py-files=$pyfiles \
       --properties="spark.driver.extraClassPath=./$JAR_FILE,spark.executor.extraClassPath=./$JAR_FILE" \
       $script \
